version: "3"

tasks:
  install-postgres:
    # Note: The Bitnami Helm chart for PostgreSQL was previously used here.
    # It was replaced with a direct Kubernetes manifest because Bitnami’s charts
    # and container images are no longer freely accessible for public use.
    # The manifest now uses the official postgres:16 image from Docker Hub.
    desc: "Deploy PostgreSQL using direct Kubernetes manifests"
    cmds:
      - kubectl create namespace postgres --dry-run=client -o yaml | kubectl apply -f -
      - kubectl apply -f postgres-simple.yaml

  apply-initial-db-migration-job:
    desc: "Run init.sql script against the DB"
    cmds:
      - "kubectl apply -f Secret.db-password.yaml"
      - "kubectl apply -f Job.db-migrator.yaml"